# Generated by Django 5.1.2 on 2024-11-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to='portfolio.userprofile', verbose_name='User Profile'),
        ),
    ]
