# Generated by Django 5.1.2 on 2024-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_about_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ('he/they', 'He/They'), ('she/they', 'She/They'), ('custom', 'Custom')], max_length=10, verbose_name='Preferred Pronouns'),
        ),
    ]
